/*
ORDER BY

SERVE PARA ORDERNAR OS RESULTADOS EM ORDEM CRESCENTE OU DECRESCENTE

SELECT <nome da coluna> FROM <nome da tabela> ORDER BY <nome da coluna> ASC ou DESC
*/

SELECT * FROM Person.Person ORDER BY FirstName ASC 

-- ASSIM ESTÁ DEIXANDO EM ORDEM CRESCENTE O PRIMEIRO NOME E DEPOIS EM ORDEM DECRESCENTE O ÚLTIMO NOME
SELECT FirstName, LastName FROM Person.Person ORDER BY FirstName ASC, LastName DESC

-- TAMBÉM É POSSÍVEL COLOCAR EM ORDEM POR COLUNAS QUE NÃO ESTÃO SENDO SELECIONADAS
SELECT FirstName, LastName FROM Person.Person ORDER BY MiddleName ASC

-- Desafio 1
SELECT * FROM Production.Product