/*
BETWEEN

É USADO PARA ENCONTRAR UM VALOR ENTRE UM VALOR MÍNIMO E VALOR MÁXIMO

<valor> BETWEEN <mínimo> AND <máximo>

SERIA A MESMA COISA QUE:

<valor> >= <mínimo> AND <valor> <= <máximo>
*/

-- ESTÁ EXIBINDO OS PRODUTOS QUE ESTÃO COM O VALOR ENTRE 1000 E 1500, CASO COLOQUE O NOT, ELE IRÁ EXIBIR TODOS QUE NÃO ESTÃO ENTRE 100 E 1500
SELECT * FROM Production.Product WHERE ListPrice /* NOT */ BETWEEN 1000 AND 1500

-- TAMBÉM É POSSÍVEL FAZER COM DATA
SELECT * FROM HumanResources.Employee WHERE HireDate BETWEEN '2009/01/01' AND '2010/01/01' ORDER BY HireDate

