/*
LIKE

É USADO PARA ENCONTRAR ALGUM DADO NO BANCO, QUE VOCÊ SABE QUE O DADO COMEÇA COM ALGO, PORÉM, NÃO SABE ELE INTEIRO.
SERIA COMO ENCONTRAR UMA PESSOA QUE VOCÊ SABE QUE O NOME DELA ERA ovi...alguma coisa

SELECT * FROM Person.Person WHERE FirstName LIKE 'ovi%'

O SINAL DE PORCENTAGEM SIGNIFICA QUE NÃO IMPORTA O QUE VEM DEPOIS, SOMENTE O QUE DIGITOU ANTES DELE OU DEPOIS
*/

-- ASSIM MOSTRARÁ TUDO O QUE COMEÇA COM OVI, INDEPENDENTEMENTE DO QUE VEM DEPOIS
SELECT * FROM Person.Person WHERE FirstName LIKE 'ovi%'

-- ASSIM MOSTRARÁ TUDO O QUE TERMINA COM TO, INDEPENDENTEMENTE DO QUE VEM ANTES
SELECT * FROM Person.Person WHERE FirstName LIKE '%to'

-- ASSIM MOSTRARÁ TUDO O QUE CONTENHA NO MEIO O ESSA, INDEPENDENTEMENTE DO QUE VEM ANTES OU DEPOIS
SELECT * FROM Person.Person WHERE FirstName LIKE '%essa%'

-- É POSSÍVEL TAMBÉM, DIZER QUANTOS CARACTERES TEM ANTES OU DEPOIS DO QUE VOCÊ DESEJA PROCURAR
-- ASSIM ESTÁ DIZENDO PARA PROCURAR TUDO QUE TERMINA COM RO, PORÉM, QUE TEM APENAS UM CARACTERE DEPOIS DO RO
SELECT * FROM Person.Person WHERE FirstName LIKE '%ro_'