/*
HAVING

O HAVING É BASICAMENTE USADO EM JUNÇÃO COM O GROUP BY PARA FILTRAR RESULTADOS DE UM AGRUPAMENTO

É COMO SE FOSSE UM WHERE PARA DADOS AGRUPADOS

SELECT <nome da coluna>, <FUNÇÃO DE AGREGAÇÃO>(<nome da coluna>) FROM <nome da tabela> GROUP BY <nome da coluna> HAVING <condição>
*/


-- VAMOS DIZER QUE QUEREMOS SABER QUAIS NOMES NO SISTEMA TEM UMA OCORRÊNCIA MAIOR DO QUE 10 VEZES
SELECT FirstName, COUNT(FirstName) AS QUANTIDADE FROM Person.Person GROUP BY FirstName HAVING COUNT(FirstName) = 10 ORDER BY COUNT(FirstName)

-- VAMOS DIZER QUE QUEREMOS SABER QUAIS PRODUTOS QUE NO TOTAL DE VENDAS, ESTÃO ENTRE 162K A 500K
SELECT * FROM Sales.SalesOrderDetail
SELECT ProductID, SUM(LineTotal) AS TOTAL FROM Sales.SalesOrderDetail GROUP BY ProductID HAVING SUM(LineTotal) BETWEEN 162000 AND 500000

-- VAMOS DIZER QUE QUEREMOS SABER QUAIS NOMES NO SISTEMA TEM UMA OCORRÊNCIA MAIOR QUE 10 VEZES, PORÉM, SOMENTE ONDE O TÍTULO É 'Mr.'
SELECT * FROM Person.Person
SELECT FirstName, COUNT(FirstName) AS CONTAGEM FROM Person.Person WHERE Title = 'Mr.' GROUP BY FirstName HAVING COUNT(FirstName) > 10

-- Desafio 1
SELECT * FROM Person.Address
SELECT StateProvinceID, COUNT(StateProvinceID) AS QUANTIDADE FROM Person.Address GROUP BY StateProvinceID HAVING COUNT(StateProvinceID) > 1000

-- Desafio 2
SELECT * FROM Sales.SalesOrderDetail
SELECT ProductID, AVG(LineTotal) FROM Sales.SalesOrderDetail GROUP BY ProductID HAVING AVG(LineTotal) > 1000000