/*
HAVING

O HAVING É BASICAMENTE USADO EM JUNÇÃO COM O GROUP BY PARA FILTRAR RESULTADOS DE UM AGRUPAMENTO

É COMO SE FOSSE UM WHERE PARA DADOS AGRUPADOS

SELECT <nome da coluna>, <FUNÇÃO DE AGREGAÇÃO>(<nome da coluna>) FROM <nome da tabela> GROUP BY <nome da coluna> HAVING <condição>
*/


-- VAMOS DIZER QUE QUEREMOS SABER QUAIS NOMES NO SISTEMA TEM UMA OCORRÊNCIA MAIOR DO QUE 10 VEZES
SELECT FirstName, COUNT(FirstName) AS QUANTIDADE FROM Person.Person GROUP BY FirstName HAVING COUNT(FirstName) = 10  ORDER BY COUNT(FirstName)