/*
SELECT

SERVE PARA SELECIONAR UMA COLUNA OU MAIS DE UMA TABELA

ASSIM ESTÁ SELECIONANDO APENAS UMA COLUNA DE UMA TABELA
SELECT <nome da coluna> FROM <nome da tabela>

ASSIM ESTÁ SELECIONANDO TODAS AS COLUNA DE UMA TABELA
SELECT * FROM <nome da tabela>
*/


SELECT * FROM Person.Person

SELECT Title FROM Person.Person

SELECT * FROM Person.EmailAddress

-- Desafio
SELECT FirstName, LastName FROM Person.Person