/*
DISTINCT

SERVE PARA QUANDO VOCÊ QUER OMITIR OS DADOS DUPLICADOS DE UMA TABELA, PARA QUE VOCÊ RETORNE APENAS OS DADOS ÚNICOS

SELECT DISTINCT <nome da coluna> FROM <nome da tabela>
*/


SELECT DISTINCT FirstName FROM Person.Person

-- Desafio
SELECT DISTINCT LastName FROM Person.Person