/*
ORDER BY

SERVE PARA ORDERNAR OS RESULTADOS EM ORDEM CRESCENTE OU DECRESCENTE

SELECT <nome da coluna> FROM <nome da tabela> ORDER BY <nome da coluna> ASC ou DESC

CASO DEPOIS DO NOME DA COLUNA QUE DESEJA ORDENAR, PODE-SER DEIXAR EM BRANCO, QUE POR PADRÃO É USADO O ASC
*/

SELECT * FROM Person.Person ORDER BY FirstName ASC 

-- ASSIM ESTÁ DEIXANDO EM ORDEM CRESCENTE O PRIMEIRO NOME E DEPOIS EM ORDEM DECRESCENTE O ÚLTIMO NOME
SELECT FirstName, LastName FROM Person.Person ORDER BY FirstName ASC, LastName DESC

-- TAMBÉM É POSSÍVEL COLOCAR EM ORDEM POR COLUNAS QUE NÃO ESTÃO SENDO SELECIONADAS
SELECT FirstName, LastName FROM Person.Person ORDER BY MiddleName ASC

-- Desafio 1
SELECT TOP 10 ProductID FROM Production.Product ORDER BY ListPrice DESC	

-- Desafio 2
SELECT Name, ProductNumber FROM Production.Product WHERE ProductID >= 1 AND ProductID <= 4

-- Ou

SELECT TOP 4 Name, ProductNumber FROM Production.Product ORDER BY ProductID ASC
